### ISSUE TITLE
Implement cache busting on js and css files at build time

### ISSUE THREAD

**Issue by lukestokes** [eosdac/eosdacio-website#12]
I'm thinking adding a `?t=<timestamp>` to be generated on build

**Comment by michaeljyeates** [comment]
dont the compilation scripts handle that?

**Comment by lukestokes** [comment]
Not currently. Both Andrew and I ran into situation where the css wasn't updated and it was breaking the footer until we did a hard refresh. It's a simple fix, just need to modify the template with the header that pulls in the css and js files to include something dynamic at build time.

**Comment by slyon** [comment]
great idea @lukestokes implemented in 6e7a0b31c425c37f4bd7174b06b0c4cf04c160f6
