### ISSUE TITLE
[Mobile] Improve legibility

### ISSUE THREAD

**Issue by KoyoungK** [eosdac/eosdacio-website#2]
![image](https://user-images.githubusercontent.com/36679144/52570633-2dfb7f00-2e57-11e9-9ff4-96beeeb998c6.png)

'Member Client' text overlaps with the image of the monitor behind and it's kind of hard to read.

(tested on mobile)

**Comment by slyon** [comment]
fixed in commit d037fe6a4ef884e08f54132f2e873d1a6da47a59
