### ISSUE TITLE
Some text missing

### ISSUE THREAD

**Issue by KoyoungK** [eosdac/eosdacio-website#4]
![image](https://user-images.githubusercontent.com/36679144/52570964-ff31d880-2e57-11e9-8ed7-4ec74df3c205.png)

The following text is missing some words?
Current:
eosDAC tokenholders are invited to log on to
https://members.eosdac.io to register as Members of the
and to unlock the benefits that come with your EOSDAC tokens.

To be fixed:
eosDAC tokenholders are invited to log on to
https://members.eosdac.io to register as Members of the **DAC**
and to unlock the benefits that come with **their** EOSDAC tokens.

**Comment by slyon** [comment]
fixed in 476a6d8d463e006468d17f0248290bb4f153bc78
