### ISSUE TITLE
Website Language Option

### ISSUE THREAD

**Issue by KoyoungK** [eosdac/eosdacio-website#43]
![Screenshot_22](https://user-images.githubusercontent.com/36679144/54877256-6ed7b200-4e5f-11e9-97a2-dce72967533c.png)

1. Korean is currently translated to:
한국의
but it should be fixed to 
한국어

2. Japanese should be fixed from
日本の

to

日本語

3. Brazilian (Portugese), German, Italian to be removed from the options

Thank you!

**Comment by yhaiying** [comment]
中国 ----> 简体中文
