### ISSUE TITLE
Newsletter Language Option

### ISSUE THREAD

**Issue by KoyoungK** [eosdac/eosdacio-website#5]
![image](https://user-images.githubusercontent.com/36679144/52571185-6a7baa80-2e58-11e9-9af6-d7d86aaf2aee.png)

Newsletter is currently sent out in
English
Russian
Korean
(potentially) Chinese

Could you reflect these options please?

Thanks

**Comment by slyon** [comment]
thanks for the feedback. those language options are now available.

fixed in 346f1957368044b8d16de1a3aeb490f033f96a61
