### ISSUE TITLE
[Request] More Social Media platform options

### ISSUE THREAD

**Issue by KoyoungK** [eosdac/eosdacio-website#6]
![image](https://user-images.githubusercontent.com/36679144/52571379-cb0ae780-2e58-11e9-8d35-6327c3a807db.png)

eosDAC is also active on Instgram now!
https://www.instagram.com/eosdac

also Murmur, EOS based microblogging dapp but this doesn't have a weblink...

**Comment by slyon** [comment]
fixed in commit 408b3fb8275e25b7e69d62b58133fb34494543c0
