### ISSUE TITLE
[Idea] Adding a tutorial for voting eosdacserver

### ISSUE THREAD

**Issue by KoyoungK** [eosdac/eosdacio-website#7]
![image](https://user-images.githubusercontent.com/36679144/52572419-1d4d0800-2e5b-11e9-8f9a-248fc0f1e9b2.png)

This is such a convenient way to vote for eosdac, why don't we include it on how-to-vote page?
Easier than using Greymass or other wallets - with our client members can transfer EOS/eosDAC and vote. The best tool!

**Comment by lukestokes** [comment]
Related: https://github.com/eosdac/memberclient/issues/4

I think we're cool with putting voting directly on the eosdac website.

**Comment by lukestokes** [comment]
@slyon can we assign this to you? I saw you talking with @piecesnbits about having some experience with eosjs. There's a fancy vote button already built into https://github.com/eosdac/eosdactoolkit that you can hopefully reuse much of.
