### ISSUE TITLE
Consider a one-click solution to access Member client

### ISSUE THREAD

**Issue by jbuck84** [eosdac/eosdacio-website#73]
I think it would be nice if there was a one-click solution that get's me to member client, instead of two. AFIK, fastest way in if your landing page is eosdac.io is to click 'member client' in top right and then have to click 'connect to the member client.' Just a thought. Thanks!

Could be considered for 'register as a member,' as well.

**Comment by lukestokes** [comment]
Mixed feelings about this. I always just type in "members.eosdac.io" directly. I don't go to the website first. For those that do go to the website first, I think a landing page explaining the client like we have no makes sense.

Thoughts?

**Comment by michaeljyeates** [comment]
i think it should go directly too

**Comment by piecesnbits** [comment]
make it configurable with a checkbox. checked=direct; unchecked is landing page. 
different people like different behaviour.

**Comment by lukestokes** [comment]
Should we completely remove this page https://eosdac.io/member-client/ ?

It doesn't seem to be linked to anywhere else that I can tell. The link here https://eosdac.io/tools/ goes directly to the client.

**Comment by lukestokes** [comment]
@piecesnbits not sure what you mean by a checkbox? Where would that checkbox exist and how would it work? This is for the eosdac.io website.

**Comment by piecesnbits** [comment]
![image](https://user-images.githubusercontent.com/44613132/57868260-ee9c5000-7802-11e9-8cf9-9325942d8100.png)
when clicking on the "connect to memberclient" you could show a one time popup having a checkbox "would you like to connect directly next time" and store the value in LS or as cookie.

**Comment by lukestokes** [comment]
Currently the site is just a static site with no use of cookies or local storage. Lots of sites show pop-ups concerning cookie usage, etc and I wonder if this is really important enough to add this level of complexity. Thoughts?

**Comment by piecesnbits** [comment]
cookies/localstorage is also static. but I agree its not important enough. I just wanted to come with a solution so that everyone is happy. and highlight the value of settings and customization.

**Comment by lukestokes** [comment]
I'm all about simplifying and removing complexity. I don't see anything special on that members page that isn't already mentioned on the member client home page or here https://eosdac.io/why-join/ so I'm going to create a PR to adjust the link to go directly to the member client, and I'll remove that page explaining the member client after I verify it's not being referenced anywhere else. Thanks for the discussion.

**Comment by lukestokes** [comment]
Resolved with https://github.com/eosdac/eosdacio-website/pull/78 which I'll deploy now.
